default_language_version:
    python: python3.9
repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        # override until resolved: https://github.com/ambv/black/issues/402
        files: \.pyi?$
        types: []

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
    -   id: pyupgrade
        args: ['--py36-plus']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
    -   id: codespell
        args: ["--config", ".codespellrc"]
        exclude: PyObjCTest|_metadata\.py$|\.fwinfo$|\.rtf$|\.mht$

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
      - id: flake8
        args: ["--config", ".flake8" ]
        additional_dependencies:
        - flake8-bugbear
        - flake8-deprecated
        - flake8-comprehensions
        - flake8-isort
        - flake8-quotes
        - flake8-mutable
        - flake8-todo
        - flake8-builtins
        - flake8-raise
        - flake8-tidy-imports

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
#      - id: debug-statements
